"""
unicode_converter.py - Unicode conversion, formatting, and export utilities for Tamil text.

Provides:
- Translation between Class ID and Tamil Unicode glyphs
- Unicode Hex string formatting (e.g. 'U+0B95')
- Validation and sanitization of Tamil strings
- Export utilities for Plain Text (.txt), Word Document (.docx), and PDF (.pdf)
"""

import os
import io
from typing import Dict, Any, Optional
from model.unicode_mapping import (
    CLASS_TO_UNICODE,
    UNICODE_TO_CLASS,
    get_unicode_char,
    get_unicode_codepoints,
    get_class_id,
    NUM_CLASSES
)

def format_prediction_result(class_id: int, confidence: float) -> Dict[str, Any]:
    """Formats a single prediction into a structured response."""
    tamil_char = get_unicode_char(class_id)
    codepoints = get_unicode_codepoints(class_id)
    return {
        'class_id': int(class_id),
        'unicode': tamil_char,
        'codepoints': codepoints,
        'confidence': round(float(confidence), 4),
        'confidence_percent': round(float(confidence) * 100.0, 2)
    }

def export_to_txt(text: str) -> io.BytesIO:
    """Exports Tamil Unicode string to a UTF-8 text file buffer."""
    buf = io.BytesIO()
    buf.write(text.encode('utf-8'))
    buf.seek(0)
    return buf

def export_to_docx(text: str, title: str = "Tamil Handwritten OCR Output") -> io.BytesIO:
    """Exports Tamil Unicode string to a Microsoft Word (.docx) document buffer."""
    import docx
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = docx.Document()

    # Document Title
    heading = doc.add_heading(level=1)
    run_title = heading.add_run(title)
    run_title.font.size = Pt(18)
    run_title.font.bold = True
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle / Metadata
    p_meta = doc.add_paragraph()
    r_meta = p_meta.add_run("Generated by Tamil Handwritten Character Recognition and Unicode Conversion System")
    r_meta.font.size = Pt(10)
    r_meta.font.italic = True
    r_meta.font.color.rgb = RGBColor(100, 100, 100)
    p_meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()  # spacer

    # Content Section
    p_content = doc.add_paragraph()
    r_content = p_content.add_run(text)
    r_content.font.name = 'Nirmala UI'
    r_content.font.size = Pt(24)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf

def export_to_pdf(text: str, title: str = "Tamil Handwritten OCR Output") -> io.BytesIO:
    """
    Exports Tamil text to PDF buffer using ReportLab.
    Configures Unicode TrueType font (Nirmala UI / Latha / Arial Unicode) if available.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    # Project-root-relative path to bundled open-source OFL Tamil font
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    bundled_font = os.path.join(base_dir, 'app', 'static', 'fonts', 'NotoSansTamil-Regular.ttf')

    tamil_font_name = 'Helvetica'  # fallback
    candidate_fonts = [
        (bundled_font, None),
        (r'C:\Windows\Fonts\Nirmala.ttf', None),
        (r'C:\Windows\Fonts\Nirmala.ttc', 0),
        (r'C:\Windows\Fonts\ARIALUNI.TTF', None),
        (r'C:\Windows\Fonts\latha.ttf', None),
        (r'C:\Windows\Fonts\NirmalaB.ttf', None),
    ]
    for path, subfont_idx in candidate_fonts:
        if os.path.exists(path):
            try:
                if subfont_idx is not None:
                    font = TTFont('TamilUnicodeFont', path, subfontIndex=subfont_idx)
                else:
                    font = TTFont('TamilUnicodeFont', path)
                pdfmetrics.registerFont(font)
                tamil_font_name = 'TamilUnicodeFont'
                break
            except Exception:
                continue


    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # Title
    c.setFont('Helvetica-Bold', 18)
    c.drawCentredString(width / 2.0, height - 72, title)

    # Subtitle
    c.setFont('Helvetica-Oblique', 9)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawCentredString(width / 2.0, height - 92, "uTHCD Unicode Tamil OCR Academic Project")

    # Separator Line
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.setLineWidth(1)
    c.line(54, height - 105, width - 54, height - 105)

    # Recognized Tamil Text
    c.setFillColorRGB(0.0, 0.0, 0.0)
    c.setFont(tamil_font_name, 28)
    # Draw Tamil text starting below the line
    text_y = height - 160
    # Split text into lines if multi-line
    lines = text.split('\n')
    for line in lines:
        if line.strip():
            c.drawString(72, text_y, line)
            text_y -= 40
        else:
            text_y -= 20

    c.showPage()
    c.save()
    buf.seek(0)
    return buf
